import { AppData } from "@/types";

export const seedData: AppData = {
  profile: {
    name: "Your Name",
    title: "VLSI / Embedded Systems Engineer",
    email: "you@example.com",
    phone: "+91 00000 00000",
    linkedin: "linkedin.com/in/yourprofile",
    github: "github.com/yourusername",
    portfolio: "yourportfolio.dev",
    location: "City, Country",
    about:
      "Passionate engineer with experience across VLSI design, verification, FPGA prototyping, and embedded systems development.",
  },
  domains: [
    { id: "vlsi", name: "VLSI", slug: "vlsi", enabled: true, order: 0 },
    {
      id: "rtl",
      name: "RTL Design",
      slug: "rtl",
      enabled: true,
      order: 1,
      parentId: "vlsi",
    },
    {
      id: "verification",
      name: "Verification",
      slug: "verification",
      enabled: true,
      order: 2,
      parentId: "vlsi",
    },
    {
      id: "fpga",
      name: "FPGA Design",
      slug: "fpga",
      enabled: true,
      order: 3,
      parentId: "vlsi",
    },
    {
      id: "embedded",
      name: "Embedded",
      slug: "embedded",
      enabled: true,
      order: 4,
    },
    {
      id: "pcb",
      name: "PCB Design",
      slug: "pcb",
      enabled: true,
      order: 5,
    },
  ],
  skills: [
    {
      id: "s1",
      name: "Verilog / SystemVerilog",
      category: "HDL",
      domainIds: ["vlsi", "rtl", "verification", "fpga"],
      priority: 1,
      visible: true,
    },
    {
      id: "s2",
      name: "VHDL",
      category: "HDL",
      domainIds: ["vlsi", "rtl", "fpga"],
      priority: 2,
      visible: true,
    },
    {
      id: "s3",
      name: "UVM",
      category: "Verification",
      domainIds: ["vlsi", "verification"],
      priority: 1,
      visible: true,
    },
    {
      id: "s4",
      name: "Xilinx Vivado",
      category: "EDA Tools",
      domainIds: ["fpga", "vlsi"],
      priority: 2,
      visible: true,
    },
    {
      id: "s5",
      name: "C / C++",
      category: "Programming",
      domainIds: ["embedded", "fpga"],
      priority: 1,
      visible: true,
    },
    {
      id: "s6",
      name: "FreeRTOS",
      category: "RTOS",
      domainIds: ["embedded"],
      priority: 2,
      visible: true,
    },
    {
      id: "s7",
      name: "KiCad",
      category: "PCB EDA",
      domainIds: ["pcb"],
      priority: 1,
      visible: true,
    },
    {
      id: "s8",
      name: "STM32",
      category: "Microcontroller",
      domainIds: ["embedded", "pcb"],
      priority: 1,
      visible: true,
    },
  ],
  experience: [
    {
      id: "e1",
      company: "Example Corp",
      role: "VLSI Design Engineer",
      startDate: "2023-01",
      endDate: "Present",
      location: "Bengaluru, India",
      domainIds: ["vlsi", "rtl", "verification"],
      bullets: [
        {
          id: "eb1",
          text: "Designed and verified 32-bit ALU in SystemVerilog with 100% functional coverage.",
          priority: 1,
          domainIds: ["vlsi", "rtl", "verification"],
        },
        {
          id: "eb2",
          text: "Developed UVM testbench for SPI controller, catching 5 RTL bugs pre-tapeout.",
          priority: 2,
          domainIds: ["verification"],
        },
        {
          id: "eb3",
          text: "Ported design to Xilinx Artix-7 FPGA and validated at 100 MHz.",
          priority: 3,
          domainIds: ["fpga"],
        },
      ],
    },
  ],
  education: [
    {
      id: "edu1",
      degree: "B.E. Electronics & Communication Engineering",
      institute: "Example University",
      startDate: "2019-08",
      endDate: "2023-05",
      score: "8.5 CGPA",
      location: "City, India",
    },
  ],
  projects: [
    {
      id: "p1",
      title: "RISC-V Core (RV32I)",
      domainIds: ["vlsi", "rtl", "fpga"],
      sourceLink: "https://github.com/yourusername/riscv-core",
      tools: ["SystemVerilog", "Vivado", "GTKWave"],
      bullets: [
        {
          id: "pb1",
          text: "Implemented a 5-stage pipelined RISC-V core supporting the full RV32I ISA.",
          priority: 1,
          domainIds: ["vlsi", "rtl"],
        },
        {
          id: "pb2",
          text: "Synthesized on Xilinx Artix-7; achieved 120 MHz max frequency post P&R.",
          priority: 2,
          domainIds: ["fpga"],
        },
        {
          id: "pb3",
          text: "Wrote directed and random tests; achieved 95% branch coverage.",
          priority: 3,
          domainIds: ["verification"],
        },
      ],
    },
    {
      id: "p2",
      title: "IoT Weather Station",
      domainIds: ["embedded", "pcb"],
      sourceLink: "https://github.com/yourusername/weather-station",
      tools: ["STM32", "FreeRTOS", "KiCad", "MQTT"],
      bullets: [
        {
          id: "pb4",
          text: "Designed 4-layer PCB hosting STM32F4 MCU, BME280 sensor, and ESP8266 Wi-Fi module.",
          priority: 1,
          domainIds: ["pcb"],
        },
        {
          id: "pb5",
          text: "Implemented FreeRTOS tasks for sensor sampling, MQTT publish, and display update.",
          priority: 2,
          domainIds: ["embedded"],
        },
        {
          id: "pb6",
          text: "Achieved < 5 mA average current in deep-sleep mode extending battery life to 6 months.",
          priority: 3,
          domainIds: ["embedded", "pcb"],
        },
      ],
    },
  ],
  certifications: [
    {
      id: "c1",
      name: "SystemVerilog for Verification",
      issuer: "Udemy",
      date: "2023-06",
      credentialLink: "",
      domainIds: ["vlsi", "verification"],
    },
  ],
  awards: [
    {
      id: "a1",
      title: "Best Project Award",
      organization: "Example University",
      date: "2023-05",
      description: "Awarded for RISC-V core project at final-year showcase.",
      domainIds: ["vlsi", "rtl"],
    },
  ],
  languages: [
    { id: "l1", name: "English", proficiency: "Professional" },
    { id: "l2", name: "Hindi", proficiency: "Native" },
  ],
  hobbies: [
    { id: "h1", name: "Open Source Hardware" },
    { id: "h2", name: "Electronics Tinkering" },
  ],
  references: [],
};
